version: '1.0'

steps:
  run_unit_tests:
    image: python:3
    description: Run unit tests
    commands:
        - pip install --no-cache-dir -r requirements.txt
        - pip install coverage
        - coverage run -m unittest discover --verbose
